In [13]:
from tensorflow.keras.preprocessing.text import one_hot # type: ignore
from tensorflow.keras.utils import pad_sequences # type: ignore
from tensorflow.keras.layers import Embedding # type: ignore
from keras.layers import Embedding
from tensorflow.keras.models import Sequential # type: ignore
import numpy as np

In [2]:
### sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
vocab_size = 10000

In [4]:
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[4609, 2481, 4034, 5209],
 [4609, 2481, 4034, 1024],
 [4609, 7942, 4034, 8668],
 [4072, 6959, 548, 6255, 2153],
 [4072, 6959, 548, 6255, 3213],
 [6974, 4609, 8079, 4034, 578],
 [3918, 4737, 3777, 6255]]

In [5]:
sent_length = 8

In [6]:
embedded_docs = pad_sequences(one_hot_repr, padding='post', maxlen=sent_length)
embedded_docs

array([[4609, 2481, 4034, 5209,    0,    0,    0,    0],
       [4609, 2481, 4034, 1024,    0,    0,    0,    0],
       [4609, 7942, 4034, 8668,    0,    0,    0,    0],
       [4072, 6959,  548, 6255, 2153,    0,    0,    0],
       [4072, 6959,  548, 6255, 3213,    0,    0,    0],
       [6974, 4609, 8079, 4034,  578,    0,    0,    0],
       [3918, 4737, 3777, 6255,    0,    0,    0,    0]], dtype=int32)

In [15]:
diamention = 10
model = Sequential()
model.add(Embedding(vocab_size, diamention, input_length=sent_length))
model.compile('adam', 'mse')

# Build the model explicitly (optional for debugging)
model.build(input_shape=(None, sent_length))

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


array([[[ 0.00202687,  0.01443689,  0.01367687, -0.03157741,
         -0.04322034, -0.04338099, -0.01060142,  0.03193218,
          0.03158266, -0.03816687],
        [ 0.04580578, -0.04768408, -0.00614362, -0.03841366,
         -0.0090166 , -0.04170329, -0.00952696,  0.03158509,
          0.00440468,  0.01284668],
        [ 0.01455715,  0.0335032 , -0.02585164,  0.04096632,
          0.02556813,  0.03555033, -0.00753609,  0.04321727,
         -0.03934861, -0.04916943],
        [-0.03800846,  0.04448244,  0.02150035,  0.02713909,
         -0.04134822,  0.01578197, -0.03312638,  0.02891289,
          0.03429682, -0.00418701],
        [ 0.04697187,  0.02554994,  0.0041978 ,  0.01234908,
         -0.00898218,  0.04582362,  0.04019357,  0.01821127,
         -0.0460422 ,  0.03493978],
        [ 0.04697187,  0.02554994,  0.0041978 ,  0.01234908,
         -0.00898218,  0.04582362,  0.04019357,  0.01821127,
         -0.0460422 ,  0.03493978],
        [ 0.04697187,  0.02554994,  0.0041978 ,  0.0

In [17]:
embedded_docs[0]

array([4609, 2481, 4034, 5209,    0,    0,    0,    0], dtype=int32)

In [19]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[ 0.00202687,  0.01443689,  0.01367687, -0.03157741, -0.04322034,
        -0.04338099, -0.01060142,  0.03193218,  0.03158266, -0.03816687],
       [ 0.04580578, -0.04768408, -0.00614362, -0.03841366, -0.0090166 ,
        -0.04170329, -0.00952696,  0.03158509,  0.00440468,  0.01284668],
       [ 0.01455715,  0.0335032 , -0.02585164,  0.04096632,  0.02556813,
         0.03555033, -0.00753609,  0.04321727, -0.03934861, -0.04916943],
       [-0.03800846,  0.04448244,  0.02150035,  0.02713909, -0.04134822,
         0.01578197, -0.03312638,  0.02891289,  0.03429682, -0.00418701],
       [ 0.04697187,  0.02554994,  0.0041978 ,  0.01234908, -0.00898218,
         0.04582362,  0.04019357,  0.01821127, -0.0460422 ,  0.03493978],
       [ 0.04697187,  0.02554994,  0.0041978 ,  0.01234908, -0.00898218,
         0.04582362,  0.04019357,  0.01821127, -0.0460422 ,  0.03493978],
       [ 0.04697187,  0.02554994,  0.0041978 ,  0.01234908, -0.00898218,
         0.04582362,  0.04019357,  0.01821127